spring:
  profiles:
    include: secret
  main:
    allow-circular-references: 'true'
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/project-kim?useUnicode=true&characterEncoding=utf8
    username: root
    password: 7410
  session:
    jdbc:
      initialize-schema: always

  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  port: 8090
