spring:
  profiles:
    include: oauth
  main:
    allow-circular-references: 'true'
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/project-kim?useUnicode=true&characterEncoding=utf8
    username: root
    password: 7410
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create

server:
  port: 8090
